### ISSUE TITLE
Probably a mistake in the quickstart.md

### ISSUE THREAD

**Issue by lukasged** [oracle/weblogic-image-tool#26]
In the quickstart's section [Creating an image with no Internet Access](https://github.com/oracle/weblogic-image-tool/blob/release-1.0.0/site/quickstart.md#creating-an-image-with-no-internet-access), there's a command to add the latest OPatch to the cache: `imagetool cache addPatch --patchId p28186730 --version 13.9.4.0.0 --path /home/acmeuser/cache/p28186730_139400_Generic.zip`. This command specifies `--version 13.9.4.0.0`, which is the version of the OPatch, but the documentation of the command `imagetool cache addPatch` (as per running `imagetool cache addPatch help`) indicates that the argument `--version` refers to the  `version of mw this patch is for. Ex: 12.2.1.3.0`. So it seems to be inconsistent.

Additionally, if I add an Oracle Support user credentials to the command and let it verify the integrity of the patch file, with the following command:
```
$ imagetool cache addPatch \
    --patchId p28186730 \
    --version 13.9.4.0.0 \
    --path "${CACHE_DIR}/p28186730_139400_Generic.zip" \
    --user ${ORACLE_SUPPORT_USER} \
    --password ${ORACLE_SUPPORT_PASSWORD}
```
I get the following error:
```
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.oracle.weblogic.imagetool.cli.cache.AddPatchEntry@363ee3a2): java.io.IOException: Failed to determine release number for category wls, version 13.9.4.0.0
        at picocli.CommandLine.execute(CommandLine.java:1063)
        at picocli.CommandLine.access$900(CommandLine.java:142)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:1214)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1405)
        at com.oracle.weblogic.imagetool.cli.WLSCommandLine.call(WLSCommandLine.java:37)
        at com.oracle.weblogic.imagetool.cli.WLSCommandLine.call(WLSCommandLine.java:16)
        at com.oracle.weblogic.imagetool.cli.CLIDriver.main(CLIDriver.java:50)
Caused by: java.io.IOException: Failed to determine release number for category wls, version 13.9.4.0.0
        at com.oracle.weblogic.imagetool.util.ARUUtil.getReleaseNumber(ARUUtil.java:503)
        at com.oracle.weblogic.imagetool.util.ARUUtil.getPatchDetail(ARUUtil.java:292)
        at com.oracle.weblogic.imagetool.cli.cache.AddPatchEntry.validateAndAddToCache(AddPatchEntry.java:86)
        at com.oracle.weblogic.imagetool.cli.cache.AddPatchEntry.call(AddPatchEntry.java:58)
        at com.oracle.weblogic.imagetool.cli.cache.AddPatchEntry.call(AddPatchEntry.java:27)
        at picocli.CommandLine.execute(CommandLine.java:1056)
        ... 8 more
```

which I suppose is related to the `--version` argument.

If I change `--version` to the WLS version `12.2.1.3.0` and also add `--type wls`, the following is the complete command I run and its resulting error:
```
$ imagetool cache addPatch \
    --type wls \
    --version 12.2.1.3.0 \
    --patchId p28186730 \
    --path "${CACHE_DIR}/p28186730_139400_Generic.zip" \
    --user ${ORACLE_SUPPORT_USER} \
    --password ${ORACLE_SUPPORT_PASSWORD}
[2019-06-14 15:36:05] [com.oracle.weblogic.imagetool.cli.CLIDriver] [SEVERE ] Response code: -1, message: Unable to find patchId p28186730 on Oracle Support
```

It seems that for now, the only working way of adding the latest OPatch patch to the cache is using the offline version of the command, without specifying the arguments `--username` and `--password`.

I'm using the release `1.0.0`

**Comment by jshum2479** [comment]
This is kind of a bug.  Opatch's patch need special handling - so that the key in the cache is ###_opatch=<file location>   and when you specify user name/password without a type then it's assume weblogic.  Since the product type for the patch is opatch and therefore the validation failed.  We are going to remove the validation.

**Comment by jshum2479** [comment]
The latest code in master no longer requires user credentials for cache addPatch, closing for now
