### ISSUE TITLE
Remove docker daemon dependency for option '--dryRun'

### ISSUE THREAD

**Issue by galiacheng** [oracle/weblogic-image-tool#305]
Hello team, we want to generate the image docker file using weblogic image tool in a container with no docker daemon installed.
I found the image tool depends on docker daemon even skipping Docker build execution with option `--dryRun`
Is that possible to remove daemon dependency for option  `--dryRun` ?
Attach the error message here:
```
bash-5.0# ./imagetool/bin/imagetool.sh update \         
--tag model-in-image:WLS-v1 \
--fromImage ${wlsImagePath} \
--wdtModel ${acrSourcePath}/model.yaml \
--wdtVariables ${acrSourcePath}/model.properties \
--wdtArchive ${acrSourcePath}/archive.zip \
--wdtModelOnly \
--wdtDomainType WLS \
--chown oracle:root \
--dryRun \
>${outputDockerFile}
[INFO   ] WebLogic Image Tool version 1.9.15
[INFO   ] Image Tool build ID: 640de789-961c-4628-bbde-ecb80003227e
[INFO   ] Temporary directory used for image build context: /root/wlsimgbuilder_temp14463571140350399862
java.io.IOException: Build command failed with error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

        at com.oracle.weblogic.imagetool.util.Utils.processError(Utils.java:290)
        at com.oracle.weblogic.imagetool.util.Utils.runDockerCommand(Utils.java:268)
        at com.oracle.weblogic.imagetool.util.Utils.removeIntermediateDockerImages(Utils.java:749)
        at com.oracle.weblogic.imagetool.cli.menu.UpdateImage.call(UpdateImage.java:171)
        at com.oracle.weblogic.imagetool.cli.menu.UpdateImage.call(UpdateImage.java:33)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at com.oracle.weblogic.imagetool.cli.ImageTool.run(ImageTool.java:89)
        at com.oracle.weblogic.imagetool.cli.ImageTool.main(ImageTool.java:56)
```

**Comment by ddsharpe** [comment]
Whenever the `--fromImage` is not the default, Image Tool inspects the provided image to determine what is supposed to be done and where the executables are located, such as Java and WLST for WDT.  For `update`, I don't think this will be possible or practical to do.
